# --------------- #
#   main config   #
# --------------- #
markdown: rdiscount
#pygments: true
highlighter: pygments
paginate: 5
permalink: /blog/:year/:month/:day/:title.html
exclude: [node_modules,Gruntfile.js,README.md,package.json]

# --------------- #
#  custom config  #
# --------------- #
blogroot: 'http://nunumick.github.io'
blogname: '默尘'
blogdesc: '--  小隐于山，中隐于市，大隐于心 --'
blogauthor: 'nunumick'
