# --------------- #
#  site cn config  #
# --------------- #
url: https://life.nunumick.cn
location: cn
icp: 浙ICP备2024067329号-1
security: 浙公网安备33010602013491号
blogroot: https://life.nunumick.cn
cdnroot: ""
ga: G-NLXX0LMMX0
gtm: GTM-P5ZC8BVN
gads: ""

