# --------------- #
#  custom config  #
# --------------- #
url: https://nunumick.github.io
# 不使用baseurl，会整站 blog/ 作为跟目录
base_url: /blog
blogroot: https://nunumick.github.io
cdnroot: https://gcore.jsdelivr.net/gh/nunumick/nunumick.github.com
blogname: 默尘
blogdesc: --  小隐于山，中隐于市，大隐于心 --
blogauthor: nunumick
ga: G-07CJTP6XHK
gtm: GTM-T6GJZH7T

# --------------- #
#   main config   #
# --------------- #
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title.html
exclude: [Gemfile, Gemfile.lock, node_modules, Gruntfile.js, README.md, package.json]
excerpt_separator: <!--more-->
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
# - jekyll-webp
paginate: 5
paginate_path: /blog/page:num/

# Markdown Processors
kramdown:
  input             : GFM
  syntax_highlighter: rouge

# Local Archives by archives plugin
# Not support on github
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-categories-local
    tag: archive-tags-local
  permalinks:
    tag: /blog/tags/:name/
    category: /blog/categories/:name/

# Custom Archives
# archives: github archives workflow
# lists: posts and tags collections
collections:
  archives:
    output: true
    permalink: /blog/:path/
  lists:
    output: true
    permalink: /blog/:path/
