# --------------- #
#   main config   #
# --------------- #
markdown: rdiscount
pygments: true
paginate: 5
permalink: /blog/:year/:month/:day/:title.html

# --------------- #
#  custom config  #
# --------------- #
blogroot: 'http://blog.nunumick.taobao.net'
blogname: '默尘'
blogdesc: '--  小隐于山，中隐于市，大隐于心 --'
blogauthor: 'nunumick'
