name: Generate Jekyll Archives
# description: Generate categories, tags and years archive files.
# 触发条件修改为在deploy部署后，post更新page构建部署，archivedata完成更新后再触发archive文件生成。
on: deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Jekyll Blog Archive
        uses: nunumick/jekyll-blog-archive-workflow@v1.0.0
        with:
          archive_url: "https://nunumick.github.io/blog/archivedata"
          archive_folder_path: "_archives"

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git add --all
          git commit -m "Created and updated archive files." || echo "No changes to commit."
          git push origin master || echo "No changes to push."
